# Generated by Django 4.0.4 on 2022-04-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_comment_dislikes_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='likes',
        ),
    ]
