# Generated by Django 4.0.4 on 2022-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
