# Generated by Django 4.0.4 on 2022-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
